author: Spotify
author_url: https://hubs.spotify.net
copyright: Copyright © 2015-2016 Spotify AB
readme: README.md

documentation: documentation/*.md

module: HubFramework
module_version: v1.0.0

output: documentation/output
theme: fullwidth

github_url: https://ghe.spotify.net/iOS/HubFramework
github_file_prefix: https://ghe.spotify.net/iOS/HubFramework/tree/master

docset_icon: documentation/resources/docset-icon@2x.png
dash_url: https://ghe.spotify.net/pages/iOS/HubFramework/docsets/feed.xml

clean: true
objc: true
sdk: iphonesimulator

framework_root: .
umbrella_header: include/HubFramework/HubFramework.h
source_directory: sources
