branches:
  only:
    - master
    - /^release-.*$/

language: objective-c

bundler_args: --without documentation --without development --deployment --jobs=3 --retry=3

script:
  - if [[ "$SKIP_CI" != "YES" ]]; then
      fastlane ci_all;
    fi
  - if [[ "$UPDATE_DOCUMENTATION" == "YES" ]]; then
      fastlane update_docs;
    fi
  # This is a workaround for a Travis-CI bug where the log might get cut-off.
  # See the [Travis-CI issue #4716](https://github.com/travis-ci/travis-ci/issues/4716).
  - sleep 3

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - IS_MASTER_BRANCH="$([[ "$TRAVIS_BRANCH" == "master" ]] && echo -n "YES")"

matrix:
  fast_finish: true
  include:
    # Main job; builds and runs everything.
    - osx_image: xcode8
    # Compatibility job; makes sure the library is buildable by Xcode 7.3.1
    - osx_image: xcode7.3
      env: LINT=NO      BUILD_DEMO_APP=NO
    # Update our documentation. Only true on a push to master build.
    - osx_image: xcode8
      env: SKIP_CI=YES  UPDATE_DOCUMENTATION="$IS_MASTER_BRANCH"

cache: bundler

notifications:
  email: false
